<?xml version="1.0" encoding="UTF-8"?>
<!--
    $Author: SZ  
    $Date: 2013-11-20 下午05:27:44  
    $Revision: 1.0  
    $Purpose: 
-->
<bm:model xmlns:e="aurora.service.exception" xmlns:bm="http://www.aurora-framework.org/schema/bm">
    <bm:operations>
        <bm:operation name="execute">
            <bm:update-sql><![CDATA[
                begin
                    sys_login_pkg.oa_nocheck_domain_account
                    (
                        p_account=>${@user_name},
                        p_result =>${@result},
                        p_provider_url =>${@provider_url},
                        p_domain =>${@domain}
                    );
                end;]]></bm:update-sql>
            <bm:parameters>
                <bm:parameter name="user_name" input="true" output="false"/>
                <bm:parameter name="result" inputPath="@result" output="true" outputPath="@result"/>
                <bm:parameter name="provider_url" inputPath="@provider_url" output="true" outputPath="@provider_url"/>
                <bm:parameter name="domain" inputPath="@domain" output="true" outputPath="@domain"/>
            </bm:parameters>
        </bm:operation>
    </bm:operations>
    <e:exception-descriptor-config>
        <e:exception-descriptor exception="java.sql.SQLException" handleClass="aurora.database.SQLExceptionDescriptor">
            <e:error-message code="1" message="EXP_EMPLOYEES.EMPLOYEE_CODE_DISTINCT"/>
        </e:exception-descriptor>
    </e:exception-descriptor-config>
</bm:model>
